### ISSUE TITLE
Update supported Python versions

### ISSUE THREAD

**Issue by jugmac00** [morepath/more.cors#6]
- drop support for Python versions < 3.6
- add support for Python versions 3.7, 3.8 (if missing)
- fix linting errors (if present)

If you are a beginner, and need to help for this issue, especially during Hacktoberfest, please comment here or reach out to me via https://jugmac00.github.io/

**Comment by gdev12** [comment]
Hello, I am participating on Hacktoberfest and would like to be assigned to work on this.

**Comment by jugmac00** [comment]
@gdev12 Glad to hear!

Just a couple of days ago, pretty much the same task was done by a Python beginner with a little support by me.

If you want, you can read a bit here: https://github.com/morepath/morepath_cerebral_todomvc/issues/2

Other than that - waiting for your contribution in October - if you have any questions, please do not hesitate to ask me.

**Comment by gdev12** [comment]
@jugmac00 I noticed that the requested changes regarding this issue have been made and merged 3 days ago. Is there anything else that needs to be done?

**Comment by jugmac00** [comment]
I am sorry, I seem to have completely forget to check the issues first.

There is nothing more to do here.

If you cannot find another well suited issue for Hacktoberfest, please drop me a line (see profile or @jugmac00 on Twitter). Please also tell me your skill level - there are many projects out there which need some help.
